apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  annotations:
spec:
  type: {{ .Values.walletconnect.service.type }}
  selector:
    app: {{ template "fullname" . }}
  ports:
    - name: {{ template "fullname" . }}-port
      protocol: TCP
      port: {{ .Values.walletconnect.service.port }}
      targetPort: {{ .Values.walletconnect.service.port }}
